### ISSUE TITLE
Video research & review

### ISSUE THREAD

**Issue by Coding-Edwar** [msimbo/codeofhonors-jobs-tracker-v1v2#17] opened 2021-01-08 06:31 UTC
Wed 12/23/20 Session 10-12pm  TIME: 1:11:00

https://web.microsoftstream.com/video/607f0c13-a4f7-450a-852f-a49883ae2033

**Comment by a4ayad** [comment] 2021-01-15 12:51
Closing this issue because it is a duplicate of issue #7. Copied the info into #7.

**Closed as completed by a4ayad** 2021-01-15 12:51 UTC
